version: '3'

services:
  couchbase:
    image: couchbase-custom
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=123456
      - COUCHBASE_BUCKET=Todo

  golang:
    image: backend
    ports:
      - 8081:8081
    environment:
      - COUCHBASE_HOST=couchbase
      - COUCHBASE_BUCKET=default
    restart: always